### ISSUE TITLE
Refactor Data.Vector.NonEmpty to pcg-utilities library

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#107]
The `Data.Vector.NonEmpty` module is self contained and is a very primitive utility data structure for PCG. It should be moved to `pcg-utilities` package and have some test suites added.

**Comment by Boarders** [comment]
This is resolved here https://github.com/amnh/PCG/commit/0ef1b18bbf1097970344a8fd692da4e2755ca320.
