### ISSUE TITLE
Refactor out Data.TCM module into a sub library

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#108]
This module is self contained. It requires moving some files from the `ffi` director into the new sub library.

This was once a sub library, but Cabal < 2.4 had build issues with the `ffi` bindings being part of a separate library (linker errors). These build issues should be resolved now with the newer versions of cabal.

The module `Bio.Metadata.MetricRepresentation` is also self-contained and should also be moved into this sub library as `Data.MetricRepresentation` because these two modules are highly related.

**Comment by Boarders** [comment]
TCM relies on ```Bio.Character.Exportable``` and ```Bio.Character.Exportable.Class```. As such I have moved these modules to pcg-utility under ```FFI.Character.Exportable``` and ```FFI.Character.Exportable.Class```.

**Comment by Boarders** [comment]
This is resolved in this commit: https://github.com/amnh/PCG/commit/a709cd8d5177aaec547122a5174c3640d1288dac.
