### ISSUE TITLE
Create a "serializing/rendering" sub library

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#109]
We should move our rendering type-classes and custom rendering functions into a sub-library which is data agnostic.

Two candidate modules to be moved:
  * `Text.Newick`
  * `Text.XML.*`

Formalize the "DATA" rendering functionality place a type class in `Text.PhlyogeneticData`.

Move custom rendering functions into appropriate internal modules that can be used for some of the "REPORT" command output functionality.

**Comment by Boarders** [comment]
This is resolved here https://github.com/amnh/PCG/commit/91e8b5c2c2676afb6aed38fab6e03106eec2f4d5.
