### ISSUE TITLE
Refactor out the "Data Normalization" modules into a sub library

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#113]
The data normalization modules are currently awkwardly shoved into random places in `Bio` as sub-modules. Their locations should be much clearer and placed in a collective spot. We will make a `pcg-data-normalization` sub library for this purpose.

We need to move these modules:

 * `Bio.Graph.Forest.Parsed`  -> `Data.Normalization.Topological`
 * `Bio.Metadata.Parsed` -> `Data.Normalization.Metadata`
 * `Bio.Character.Parsed` -> `Data.Normalization.Character`

We should probably rename the type-classes to something like:

 * `getNormalizedTopology`
 * `getNormalizedMetadata`
 * `getNormalizedCharacters`

**Comment by Boarders** [comment]
This issue is now closed here: https://github.com/amnh/PCG/commit/e468b577994595c768086a61188f36a444fc4f3c.
