### ISSUE TITLE
Add "clustering" wagner build option

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#129]
Consider using a K-means clustering pass over the leaf set to determine how to build Wagner trees in parallel. @Boarders has a solid vision of how to move forward on implementing this.

The K-mean pass should converge in linear time with a K constant factor. The hypothesis is that this will provide a better/faster tree construction, by using clustering to determine the leaf set permutation instead of a random permutation.

**Comment by Boarders** [comment]
This feature is now (finally!) merged in this commit: https://github.com/amnh/PCG/commit/b4bb7e877d2701bc56689290060cfa2a559f25cf
