### ISSUE TITLE
Upgrade to GHC-8.8.1

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#146]
These dependencies are *currently* stopping our upgrade:

 - [x] `attoparsec`
 - [x] `cabal-doctest`
 - [x] `microlens`
 - [x] `polyparse`
 - [x] `vector-th-unbox`

**Comment by recursion-ninja** [comment]
Cabal still isn't building with `ghc-8.8.1` because of `cassava`, our barely used CSV rendering dependency.

I think it's because `cabal-3.0` handles the packages flags slightly differently, and `cassava` uses a lot of `cabal` build flags to decide which `bytestring` library to use.

**Comment by recursion-ninja** [comment]
Let's drop the `cassava` dependency and use `unlines . fmap (intercalate ",")`.

**Comment by wardwheeler** [comment]
There’s a solution

Sent from mobile


On Oct 9, 2019, at 10:15 AM, recursion-ninja <notifications@github.com> wrote:

﻿
EXTERNAL SENDER


Let's drop the cassava dependency and use unlines . fmap (intercalate ",").

**Comment by recursion-ninja** [comment]
We removed the `cassava` dependency from our project. See 75222d520f6c1031632d5d83b423602cca04f55a.

Our project now builds with `ghc-8.8.1` on both `cabal-3.0` and `stack`. We can consider merging the `ghc-8.8.1` branch into `master` in the near future.

**Comment by Boarders** [comment]
Excellent to hear!

**Comment by wardwheeler** [comment]
Nice

Sent from mobile


On Oct 9, 2019, at 1:21 PM, recursion-ninja <notifications@github.com> wrote:

﻿
EXTERNAL SENDER


We removed the cassava dependency from our project. See 75222d5<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famnh%2FPCG%2Fcommit%2F75222d520f6c1031632d5d83b423602cca04f55a&data=02%7C01%7Cwheeler%40amnh.org%7Ce11fbde3fd8b43702a1208d74cdd0e07%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637062384614830406&sdata=K6QSkxJCE3LVfam36xEEgc36O51PFL%2BZWiULMA1OkwQ%3D&reserved=0>.

Our project now builds with ghc-8.8.1 on both cabal-3.0 and stack. We can consider merging the ghc-8.8.1 branch into master in the near future.

**Comment by recursion-ninja** [comment]
`master` is compiling `ghc-8.8.1`. See a9c71f97e1d5e4a07dae6741897b5481488b9277.
