### ISSUE TITLE
Use hpack for cabal file specification

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#156]
We repeat ourselves a lot in our various sub libraries. One such example is the GHC flags which are the same in every library.

`hpack` promises to reduce duplication.

See branch `hpack-generation` for changes.

Invoke the following to generate the `.cabal` files:

 ```$ make run-hpack```

**Comment by recursion-ninja** [comment]
Also, builds with `cabal` are failing because `cassava` is messed up, and `cassava` is a dependency of `criterion`...

Builds with `stack` work because of some dependency graph black magic.

**Comment by Boarders** [comment]
I am not too keen on giving up cabal builds so we might want to hold off on a merge until it is solved.

**Comment by recursion-ninja** [comment]
I agree. However I don't think `hpack` caused this issue, I think it just brought it to our attention again by requiring all dependencies for all build targets. I think that if you try and build any build target that depends on `criterion` you will encounter this problem. We can test my hypothesis by trying to build the `pcg-file-parsers:bench-time` build target on `master`, which depends on `criterion` and does not use `hpack`.

**Comment by Boarders** [comment]
Yes, I just don't think we should break the ability to build any library with cabal until it is fixed.

**Comment by recursion-ninja** [comment]
Yeah, again I agree. I think the real solution is probably having the library maintainer of cassava fix their library instead of us trying to apply bandaids. I can open an issue when I return.

**Comment by recursion-ninja** [comment]
I opened an issue: https://github.com/haskell-hvr/cassava/issues/177

**Comment by recursion-ninja** [comment]
I got information from @RyanScott to resolve the cassava for us.

**Comment by recursion-ninja** [comment]
We should explore #158, and decide between which approach offers the easiest maintainability.

**Comment by recursion-ninja** [comment]
Decided on #158 over this approach.
