### ISSUE TITLE
Add exit clean up

### ISSUE THREAD

**Issue by Boarders** [amnh/PCG#157]
Using the bracket function from [here](http://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Exception.html#v:bracket) we can add the ability to clean up after an operation. If my understanding is correct when the GHC runtime system receives a SIGINT (e.g. if the user hits C-c) this cleanup action will be run. 

In discussions with @recursion-ninja  we decided on where this should be added so that we have an interrupt handler for the various different evaluate commands. Our idea was roughly that if, for instance, you have done a build command (which should probably be added as a global settings flag) then we save the work. If you are in the middle of reporting output then that finishes (unless the user absolutely does want to stop the program). This would also fit nicely into any more interactive top level we might add in the future.

**Comment by recursion-ninja** [comment]
This should be fairly trivial to implement in `main` using the modules [`Control.Concurrent.MVar`][3] from [`base`][4] and [`System.Posix.Signals`][1] from the [`unix`][2] package along with the technique described [here][0].

[0]: https://stackoverflow.com/questions/18430748/killing-a-haskell-binary/18430872#answer-18430872
[1]: http://hackage.haskell.org/package/unix/docs/System-Posix-Signals.html
[2]: http://hackage.haskell.org/package/unix
[3]: https://hackage.haskell.org/package/base/docs/Control-Concurrent-MVar.html
[4]: https://hackage.haskell.org/package/base

**Comment by recursion-ninja** [comment]
This functionality has been implemented using the technique described above. See b2f2bc5503c101df57b66b676709134847305914.
