### ISSUE TITLE
Address TODOs in main codebase

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#16]
<a href="https://github.com/ima-hima"><img src="https://avatars0.githubusercontent.com/u/13487794?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ima-hima](https://github.com/ima-hima)**
_Wednesday Mar 29, 2017 at 15:02 GMT_
_Originally opened as https://github.com/ima-hima/PCG/issues/16_

----

**Comment by recursion-ninja** [comment]
There are 17 TODOs remaining in the `app, `src`, `utils`, and `test` directories. All of these are able to be addressed given the current state of our code base. We should address each of them before the v0.2.0 release to alleviate some technical debt.

There are 74 TODOs in the `ffi` directory. We will ignore those for the time being and create a separate issue for addressing TODOs related to the FFI.

  * [ ] app/PCG/Command/Read/Evaluate.hs:74
  * [ ] app/PCG/Command/Echo/Evaluate.hs:14
  * [ ] app/PCG/Command/Report/Evaluate.hs:41
  * [ ] app/PCG/Command/Report/Metadata.hs:26
  * [ ] src/Bio/Character/Parsed/Class.hs:61
  * [ ] src/Bio/Metadata/Parsed.hs:132
  * [ ] src/Bio/Metadata/Parsed.hs:256
  * [ ] src/Bio/Graph/PhylogeneticDAG/Internal.hs:108
  * [ ] src/Bio/Graph/ReferenceDAG/Internal.hs:240    
  * [ ] src/Bio/Graph/ReferenceDAG/Internal.hs:987
  * [ ] src/Bio/Sequence.hs:98
  * [ ] src/Control/Evaluation.hs:18
  * [ ] src/Analysis/Parsimony/Sankoff/Internal.hs:102
  * [ ] src/Analysis/Parsimony/Sankoff/Internal.hs:150
  * [ ] src/Analysis/Parsimony/Dynamic/DirectOptimization/Internal.hs:263
  * [ ] src/Analysis/Parsimony/Additive/Internal.hs:35
  * [ ] src/Test/Custom/Constructions.hs:22

**Comment by ima-hima** [comment]
I will volunteer to make very, very slow progress on writing tests for the Parsimony crap I wrote. Good enough?

e

**Comment by recursion-ninja** [comment]
Aside from the `Nexus` parser module, and the C/C++ code, all the TODOs have been addressed.

**Comment by ima-hima** [comment]
I thought you’d carved out the C++ code?

i’ll look at this stuff this week. I think I have time, and I’m planning to come in to the museum tomorrow, anyway.

e
