### ISSUE TITLE
getSubsetIndex bug

### ISSUE THREAD

**Issue by Boarders** [amnh/PCG#165]
Currently on master several of the tests to do with dynamic character decoding fail (with some throwing exceptions). I eventually tracked down that this is an error in the unsorted branch of the `getSubsetIndex` code. In particular I added the following test:

```haskell
subsetIndex :: TestTree
subsetIndex =
  testGroup "Subset Index Tests:"
      [ HU.testCase "getSortedLookup agrees for sorted and unsorted alphabets" sortedLookup
      ]
  where
    alphabet :: Alphabet String
    alphabet = fromSymbols ["0","1","2"]

    sortedAlphabet :: Alphabet String
    sortedAlphabet = alphabet {isSorted = True}

    sortedLookup :: Assertion
    sortedLookup =
     (getSubsetIndex alphabet (Set.singleton "1"))
      @?=
     (getSubsetIndex sortedAlphabet (Set.singleton "1"))
```

This gives the following:
```shell
    Subset Index Tests:
      getSortedLookup agrees for sorted and unsorted alphabets:                      FAIL
        lib/alphabet/test/Data/Alphabet/Test.hs:158:
        expected: 2
         but got: 0
```

For now I am going to fix the error in the unsorted function but it is probably worth moving towards having an invariant that all alphabets are always sorted and deleting code that doesn't assume otherwise.

I should note that using only sorted alphabets fixes all the tests from `core:data-structures` to pass.

**Comment by recursion-ninja** [comment]
Can't sort all alphabets Alphabets of "additive characters" must remain in their input order.

**Comment by Boarders** [comment]
Ok, I have a fix for the unsorted code so I will merge that.

**Comment by Boarders** [comment]
This is hopefully now fixed [here](https://github.com/amnh/PCG/commit/36dd626d1e95cb7fb018bfaa2ed4124a3b18140e)

I don't know if this is most efficient but there is at least some pretty extensive testing in place [here](https://github.com/amnh/PCG/commit/bed1a576ba2dc5a70ef1de3ffea23ab7aa3943de) to ensure that any optimisations remain correct.
