### ISSUE TITLE
Publish our method of generating the "resolution cache" for all rootings in a Phylogenetic Network

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#35]
Generating all the re-rootings in a binary tree can be performed with memoization in `O(k*n)` time where `k` is the cost of the binary operation between two subtrees. This memoization technique relies on the fact that all vertices have in-degree 1 which allows for unambiguous directionality from any rooting and also forbids cycles from being formed. With a phylogenetic that allows for verticies with in-degree 2 a naive application of the same memoization approach will not work as cycles can be formed trivially and edge directionality becomes ambiguous in potential cycles. 

We will show how to efficiently prevent cycles in a memoized manner. This will involve creating a resolution cache at each vertex that could be included in an cycle when the edges are undirected. for each potential directed cycle in the undirected graph we will consider the case that a single edge in the cycle has it's directionality reversed. By accumulating all possible DAGs generated this way and placing the substructures of these DAGs in a memoized resolution cache at each vertex, we can efficiently compute the resolution cache of each possible edge rooting in the phylogenetic network.

Whether this is novel enough for it's own publication or too detailed to be included in another publication will have to be determined after a draft has been produced.

**Comment by ima-hima** [comment]
Will be included in #32.
