### ISSUE TITLE
Use DOT files as acceptable graph input

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#41]
The `.dot` file specification for rendering graphs via programs like `graphviz` contains all the necessary information to construct phylogenetic DAGs as input. We should use an existing Haskell `dot` file parser, perhaps [`graphviz`](https://hackage.haskell.org/package/graphviz) or [`language-dot`](https://hackage.haskell.org/package/language-dot), to read `dot` files as input for convenience.

**Comment by ima-hima** [comment]
Exhibitions Dept,

I saw the ad on Authentic Jobs for a freelance web developer and I wanted to express my interest. I am a software developer working at Heitman-Ford, LLC. I am also a scientist and researcher finishing up a job in phylogenetics at AMNH, and I maintain an anthropological morphometric database and web frontend for NYCEP. I think the intersection of my domain knowledge and technical abilities make me a good fit for the position described.

Please find my resume and cover letter attached.

Thank you,
Eric Ford
