### ISSUE TITLE
Add tests for missing data

### ISSUE THREAD

**Issue by ima-hima** [amnh/PCG#45]
Make sure that continuous, additive, non-additive, sankoff, and dynamic characters work with both missing data and _all_ data missing.

**Comment by recursion-ninja** [comment]
Add integration test that include missing data for:

 * [X] continuous
 * [X] non-additive
 * [X] additive (defective, see #90)
 * [ ] sankoff
 * [ ] dynamic (both missing elements in the sequence and missing sequences)
