### ISSUE TITLE
Goloboff Sankoff shortcuts

### ISSUE THREAD

**Issue by ima-hima** [amnh/PCG#46]
- [ ] Create new Sankoff character decoration specific to this, based on Sankoff

 - [ ] Write unit tests for said character.

**Comment by ima-hima** [comment]
I know this is closed, but as a reminder, I've done the prep work for this. I believe it doesn't have a test suite, but I'm not positive. The final few steps are yet to be done because something necessary in the... traversal, I think... wasn't in place.

Anyway, it's been so long since I read that paper that I only have a vague memory of what needs to be done, but it's more than you all have. Let me know when you're ready and I'll look at it to see how much work it will take and whether I have time.

e

**Comment by recursion-ninja** [comment]
Okay, the discussion will be in issue #42 because there were two open issues for the same task.
