### ISSUE TITLE
Add benchmarking suite

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#88]
Add a benchmarking suite for given functions. We can use `criterion` and `weigh` to measure the run-time and memory usage respectively. Try to test time and space complexities using these libraries. If we can write our own abstraction for this, that would be great.

Should also investigate how well parallelism is being utilized. Specifically strictness with data parallelism.

**Comment by recursion-ninja** [comment]
Some specific things to test:

 * [ ] Wagner build functionality to be _O(n^2)_ time complexity and _O(n)_ space complexity with respect to the input leaf set.
 * [ ] Single pass of the network build should be at worst _O(e^2)_ time complexity with respect to the input edge set. 
* [ ] Scoring a graph should be _O(n)_ time complexity with respect to the number of input characters.

**Comment by recursion-ninja** [comment]
This library might be very useful. Worth exploring:

https://github.com/mathandley/AutoBench

**Comment by Boarders** [comment]
Currently AutoBench is not on hackage and is quite hard to build with our project (e.g. it uses an earlier version of megaparsec). I think it is still worth exploring in the future if a more robust version is developed.

**Comment by recursion-ninja** [comment]
Which version of `megaparsec` is it using to build?

**Comment by Boarders** [comment]
It has the bounds: megaparsec >= 6.2 && < 6.6,

**Comment by recursion-ninja** [comment]
\*sigh\*, I had updated to `megaparsec >= 7.0 && < 8.0` for some reason, but I can't remember what it was.

If it looks promising, maybe I can make a PR to upgrade `AutoBench` to use `megaparsec >= 7.0`. The process was quite painless for me with our code base.

**Comment by recursion-ninja** [comment]
We should take the random TCM generation and tree/sequence data generation from `utils/generate-tcm.hs` and `utils/generate-data-set.hs`, respectively into testing modules. Should be useful in conjunction with `AutoBench`.

**Comment by recursion-ninja** [comment]
We have since added several benchmarking suites, though not the ones outlined above. Closing as this issue's completion is "good enough" for now. We can make a new, more specific in the future for more benchmark targets.
